backend:
  name: github
  repo: saqibj/saqibj.github.io
  branch: main
  base_url: https://github.com
  site_domain: saqibj.github.io
  auth_endpoint: https://github.com/login/oauth/authorize
  auth_scope: repo

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string", required: true }
      - { name: "date", label: "Date", widget: "datetime", format: "YYYY-MM-DD" }
      - { name: "tags", label: "Tags", widget: "list", required: false }
      - { name: "body", label: "Content", widget: "markdown" }

  - name: "projects"
    label: "Projects"
    folder: "_data/projects"
    create: true
    fields:
      - { name: "name", label: "Project Name", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "url", label: "Project URL", widget: "string" }
      - { name: "tech", label: "Technologies", widget: "list" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "about.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "body", label: "Content", widget: "markdown" }